language: java

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf && R -e "install.packages('rJava', type='source')"  && R -e "install.packages(c('devtools', 'XML', 'testthat', 'ggplot2', 'reshape2', 'plyr', 'stringr', 'tm', 'openNLP', 'NLP', 'lda', 'apcluster', 'ggdendro', 'FactoMineR', 'gridExtra', 'data.table', 'snowfall', 'slam', 'igraph', 'snow'), repos = 'http://cran.rstudio.com/')"  ; fi
 